CREATE DATABASE IF NOT EXISTS weather_app;

USE weather_app;

CREATE TABLE IF NOT EXISTS api_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  city VARCHAR(255) NOT NULL,
  request_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
